# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a767e0b2c046cd44e850bf26ec65e5dfbf6cd3ca33a844500617e00652bc8fdad63d0982a4da2f4b7e41d8df0a081ee8f0ee1c52f30fb2f19483adf6397ba140

test:
  secret_key_base: f5f65613f5b919a44352c931e1ca2b9f1976e265fc8d84d25fe1aa9d3e708ce1280c19d53d676252a4f28e041d4004b981dcfde74b67b34bf98d07596a6af4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
